// <auto-generated />
using System;
using Car_Workshop_System.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_Workshop_System.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213184258_InitialDbMigration")]
    partial class InitialDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.TechnicianAssignment", b =>
                {
                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TechnicianId", "WorkOrderId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("TechnicianAssignments", (string)null);
                });

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.Note", b =>
                {
                    b.HasOne("Car_Workshop_System.Domain.Entities.Technician", "Technician")
                        .WithMany("Notes")
                        .HasForeignKey("TechnicianId");

                    b.HasOne("Car_Workshop_System.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Notes")
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("Technician");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.TechnicianAssignment", b =>
                {
                    b.HasOne("Car_Workshop_System.Domain.Entities.Technician", "Technician")
                        .WithMany("TechnicianAssignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_Workshop_System.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("TechnicianAssignments")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.Technician", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("TechnicianAssignments");
                });

            modelBuilder.Entity("Car_Workshop_System.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("TechnicianAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
